// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.summit.notebook.domain;

import com.summit.notebook.domain.NotebookIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NotebookIntegrationTest_Roo_Configurable {
    
    declare @type: NotebookIntegrationTest: @Configurable;
    
}
